### ISSUE TITLE
MeasurementApi with group by

### ISSUE THREAD

**Issue by moonkev** [fsanaulla/chronicler#193] opened 2019-10-07 06:04 UTC
Hi @fsanaulla 

I am curious, is the measurement API able to work with group by statements? It appears that the tags are not parsed, and also only the first series from the response is parsed.

**Comment by fsanaulla** [comment] 2019-10-07 09:02
Hello @moonkev. It should, looks like a bug. I'll fix it ASAP.

**Comment by moonkev** [comment] 2019-10-07 18:11
Thanks for the quick response @fsanaulla 

As the measurement API wasn't working with group by statements, I decided to try the database API.  While I can in fact get tags with this API, as well as multiple series, it seems that it only returns the first set of fields for a given series.  While this is valid if you are only grouping by tags, if you group by time ([described here](https://docs.influxdata.com/influxdb/v1.7/query_language/data_exploration/#group-by-time-intervals)), then you can receive multiple values back.  

Here is an example query using the sample data set that influx provides for testing.

```
> select mean(water_level) from h2o_feet group by location, time(10d) fill(none)
name: h2o_feet
tags: location=coyote_creek
time                 mean
----                 ----
2015-08-13T00:00:00Z 5.255175833333332
2015-08-23T00:00:00Z 5.282439166666671
2015-09-02T00:00:00Z 5.365102959566481
2015-09-12T00:00:00Z 5.543609345794391

name: h2o_feet
tags: location=santa_monica
time                 mean
----                 ----
2015-08-13T00:00:00Z 3.3572483333333363
2015-08-23T00:00:00Z 3.374660833333338
2015-09-02T00:00:00Z 3.527653171953253
2015-09-12T00:00:00Z 3.887266586248496
```

As you can see, there are 4 points returned for each series.  However, in the returned data from calling `DatabaseApi.readGroupedJson` , which is of type `Array[(Array[String], JArray)]` the `JArray` only contains the first point in the series.  Maybe it should be `Array[(Array[String], Array[JArray])]` ?

**Comment by fsanaulla** [comment] 2019-10-07 20:20
@moonkev sorry I've forgotten that grouped API exposed only for DatabaseApi. 
You complete right it should work with the result of `GROUP BY` operation on multiple keys. I'm working on the solution.

I'll notify you when the fix will be available for use, hopefully, tomorrow.

Thank you!

**Comment by fsanaulla** [comment] 2019-10-08 16:30
Fixed, I'll deploy changes today in the evening.

**Comment by moonkev** [comment] 2019-10-09 13:28
@fsanaulla Thanks so much for the quick fix

**Comment by fsanaulla** [comment] 2019-10-09 16:15
PR https://github.com/fsanaulla/chronicler/pull/195

**Comment by fsanaulla** [comment] 2019-10-10 19:38
Merged, but some issues with Sonatype :) Hopefully, it will be available later in the evening.

**Comment by fsanaulla** [comment] 2019-10-12 10:58
Deployed, in few hours will be available for download

**Comment by fsanaulla** [comment] 2019-10-14 10:26
@moonkev 0.6.1 available, let me know if something wrong.

**Comment by moonkev** [comment] 2019-10-15 20:39
@fsanaulla Just tested out 0.6.1 and can verify group by statements are working as expected now.  I see that now an array of JArray is returned, and I can verify it is containing all points for a given series.  Unless there is anything else you wanted tested, I think it is fair to say this ticket can be closed.  Thank you again for this fix and the library in general!

**Comment by fsanaulla** [comment] 2019-10-16 10:04
@moonkev Thank you! 

We make this project better together. 

Feel free to reopen if you will discover some unexpected behavior.

**Closed by fsanaulla** 2019-10-16 10:04 UTC
Labels: bug, critical
